version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: inventory-app
    restart: always
    working_dir: /var/www
    volumes:
      - web-root-clean:/var/www
      - ./.env:/var/www/.env
    links:
      - db
    networks:
      - inventory-network

  web:
    image: nginx:alpine
    container_name: inventory-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - web-root-clean:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - inventory-network

  db:
    image: mysql:8.0
    container_name: inventory-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata-clean:/var/lib/mysql
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  dbdata-clean:
    driver: local
  web-root-clean:
    driver: local
