name: Deploy to DigitalOcean with Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/inventory-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        source: "docker-compose.yml,docker"
        target: "/var/www/inventory-app"

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          cd /var/www/inventory-app
          
          # Auto-create .env file to prevent missing file error
          rm -rf .env
          echo "APP_NAME=StockMaster" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=base64:Zlcvuy+a3FPh1jJMRKTGhWPeySXS0HqITY9hW8VuSA4=" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=http://174.138.86.39" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=172.25.0.5" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=inventory_db" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root_password" >> .env

          # Login to Docker Hub
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Pull latest image
          docker pull ${{ secrets.DOCKER_USERNAME }}/inventory-app:latest
          
          # Restart Containers
          export DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/inventory-app:latest
          docker-compose down
          
          # Start Containers
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/inventory-app:latest docker-compose --env-file .env up -d
          
          # Wait for DB
          sleep 60
          
          # Run Migrations
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/inventory-app:latest docker-compose --env-file .env run --rm app php artisan migrate --force
